### ISSUE TITLE
Komplettering, Laboration 1

### ISSUE THREAD

**Issue by 1dv449** [JuliaSivartsson/1dv449_jsigc09#1]
Komplettera laboration 1 genom att skapa en README.md-fil i laborationskatalogen och i den svara på reflektionsfrågorna + "Vad är nätneutralitet? Vad innebär Social Machine? vad är skillnaden på Web of things och Internet of things"

Svara här när klar.

**Comment by JuliaSivartsson** [comment]
Jag känner mig klar med uppgifterna, hoppas svaren är utförliga nog.

**Comment by 1dv449** [comment]
G
