### ISSUE TITLE
Komplettera för G

### ISSUE THREAD

**Issue by 1dv449** [JuliaSivartsson/1dv449_jsigc09#4]
Vad är
- Websockets
- Webstorage
- HTTP/2
- Service Workers

**Comment by JuliaSivartsson** [comment]
reflektionen är uppdaterad

**Comment by 1dv449** [comment]
Lite slarvigt skrivet på vissa ställen:
"Websocket implementeras främst i webbläsaren och på webbservrar. Det är en teknik som gör det möjligt att använda tvåvägskommunikationer över TCP (Transmission Control Protocol). Websocket är ett självständigt protokoll och gör det möjligt att ha flera interaktioner mellan webbläsare och applikation."

Så vad är skillnaden mellan HTTP och Web socket? Vad menar du med "tvåvägskommunikationer över TCP " och "att ha flera interaktioner mellan webbläsare och applikation."?

**Comment by JuliaSivartsson** [comment]
reflektionen är uppdaterad, text som har lagts till:

"Vad jag förstår det som är websockets att föredra framför HTTP när det kommer till applikationer på webben (så som chatt tjänster eller spel med flera spelare). Både HTTP och Websockets har ungefär samma "handshake" vid initiering men vid Websockets sker detta bara en gång och därefter blir svarstiden kortare med Websockets då de inte har alls lika stora HTTP headers. 
Medan HTTP använder sig av "hacks" för att kunna köra tvåvägskommunikation, så som att öppna flera anslutning (t.ex. med hjälp av iframe) så är det standard i Websockets att det ska vara tvåvägskommunikation. Alltså att det kan skickas meddelanden i båda riktningar samtidigt (du kan både ta emot och skicka samtidigt). Det är det här som kallas för full-duplex mode. 
När jag skrev att websockets innebar att det kunde vara flera interaktioner mellan webbläsare och applikation, så var slarvigt utryckt. Jag menade att det mer eller mindre går att göra flera saker samtidigt, alltså via tvåvägskommunikation då man både kan ta emot och skicka samtidigt. Detta gör svarstider kortare och i många fall blir applikationer snabbare."

**Comment by 1dv449** [comment]
OK
